# This way we don't need to create sys envs, only if we're getting them from inside the code
spring.profiles.active=local
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.format-sql=true

# This needs to be on a separated file "application-local.properties"
# spring.application.name=
# spring.datasource.url=
# spring.datasource.password=
# spring.datasource.username=
